// Mapping of keys to descriptive names
export const keyToString: { [key: string]: string } = {
    "F": "Flags",
    "M": "Markers",
    "R": "Registers",
    "SR": "String Registers",
    "VR": "Visual Registers",
    "AR": "Function Arguments",
    "DI": "Digital Inputs",
    "DO": "Digital Outputs",
    "GI": "Group Inputs",
    "GO": "Group Outputs",
    "RI": "Robot Inputs",
    "RO": "Robot Outputs",
    "UI": "User Op Panel Inputs",
    "UO": "User Op Panel Outputs",
    "SI": "Serial Inputs",
    "SO": "Serial Output",
    "SPI": "Safe Peripheral Inputs",
    "SPO": "Safe Peripheral Outputs",
    "SSI": "Safe System Inputs",
    "SSO": "Safe System Outputs",
    "CSI": "CIP Safety Inputs",
    "CSO": "CIP Safety Outputs",
    "SIR": "Safe Internal Relays",
    "CPC": "Cart. Pos. Checks",
    "CSC": "Cart. Speed Checks",
    "JPC": "Joint Pos. Checks",
    "JSC": "Joint Speed Checks",
    "NSI": "Non-Safety Inputs"
}